export enum AuditAction {
  USER_REGISTERED = 'user.registered',
  USER_LOGIN = 'user.login',
  USER_LOGOUT = 'user.logout',
  USER_EMAIL_VERIFIED = 'user.email_verified',
  USER_PASSWORD_CHANGED = 'user.password_changed',
  USER_ROLES_CHANGED = 'user.roles_changed',
  USER_DELETED = 'user.deleted',
  USER_DATA_EXPORTED = 'user.data_exported',
  PROFILE_UPDATED = 'profile.updated',
  DOCUMENT_UPLOADED = 'document.uploaded',
  DOCUMENT_DELETED = 'document.deleted',
  ASSESSMENT_STARTED = 'assessment.started',
  ASSESSMENT_COMPLETED = 'assessment.completed',
  SCORE_CALCULATED = 'score.calculated',
  SUBSCRIPTION_CREATED = 'subscription.created',
  SUBSCRIPTION_CANCELLED = 'subscription.cancelled',
  PAYMENT_RECEIVED = 'payment.received',
  PAYMENT_FAILED = 'payment.failed',
  SETTINGS_CHANGED = 'settings.changed',
  MODERATION_ACTION = 'moderation.action',
}
